version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:17.2.0 
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/FarazAshfaq/CircleCI-Nodejs/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  nodejs:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          node server.js

workflows:
  my-custom-workflow:
    jobs:
      - nodejs